name: ci

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  CI:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      GKS_ENCODING: "utf8"
      GKSwstype: "nul"

    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'  # lowest declared compat in `Project.toml`
          - '1'
          # - 'nightly'
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch:
          - x64
          # - x86
        include:
          - os: ubuntu-latest
            prefix: xvfb-run  # julia-actions/julia-runtest/blob/master/README.md

    steps:

      # Setup environment
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v1

      - uses: julia-actions/julia-buildpkg@latest

      - uses: julia-actions/julia-runtest@latest
        with:
          prefix: ${{ matrix.prefix }}  # for `xvfb-run`

      # - name: Codecov
      #   uses: julia-actions/julia-uploadcodecov@latest
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  Skip:
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
