name: ci

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  CI:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      GKS_ENCODING: "utf8"
      GKSwstype: "nul"

    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'lts'  # minimal declared julia compat in `Project.toml`
          - '1'  # latest stable
        experimental:
          - false
        os: [ubuntu-latest, windows-latest]
        arch: [x64]
        include:
          - os: ubuntu-latest
            experimental: true
            version: 'pre'  # upcoming julia version (`alpha`, `beta` or `rc`)
          - os: macos-latest
            arch: aarch64
            version: '1'
            experimental: false

    steps:

      # Setup environment
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v2

      - uses: julia-actions/julia-buildpkg@latest

      - uses: julia-actions/julia-runtest@latest
        with:
          prefix: ${{ matrix.prefix }}  # for `xvfb-run`

      - uses: julia-actions/julia-processcoverage@latest
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          file: lcov.info

  Skip:
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - name: Skip CI 🚫
        run: echo skip ci
